apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wp-manager
  name: wp-processor
rules:
  - apiGroups: ["helm.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
