apiVersion: v1
kind: ConfigMap
metadata:
  name: htaccess
  namespace: wp-manager

data:
  wordpress-htaccess.conf: |
    <IfModule mod_setenvif.c>
      SetEnvIf X-Forwarded-Proto "^https$" HTTPS
    </IfModule>
